# Generated by Django 5.1.6 on 2025-03-10 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TempChatMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Temptoken', models.IntegerField()),
                ('Message', models.CharField(max_length=100)),
                ('Type', models.CharField(max_length=100)),
                ('UserId', models.IntegerField()),
            ],
        ),
    ]
