# Generated by Django 5.1.6 on 2025-03-18 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_tempchatmaster'),
    ]

    operations = [
        migrations.CreateModel(
            name='QADataSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.answersetmaster')),
                ('Question', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.questionsetmaster')),
            ],
        ),
    ]
